# Made by Artx999 <3 👾, based apon SamKirklands file
name: 🚀 Deploy website on push
on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.domeneshop.no
        username: haldenvgs
        password: ${{ secrets.ftp_password }}
        server-dir: www/personer/takotzo/
